Update ci settings using pipenv

diff --git a/.github/workflows/irma-ci.yml b/.github/workflows/irma-ci.yml
--- a/.github/workflows/irma-ci.yml
+++ b/.github/workflows/irma-ci.yml
@@ -1,4 +1,3 @@
-
 # This is a basic workflow to help you get started with Actions
 
 name: CI
@@ -25,30 +24,33 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
-          
+
       - name: Switch to Current Branch
         run: git checkout ${{ env.BRANCH }}
-              
+
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v3
         with:
           python-version: ${{ matrix.python-version }}
-      - name: Install dependencies
+
+      - name: Install dependencies with pipenv
         run: |
-          python -m pip install --upgrade pip
-          pip install flake8 pytest pytest-cov pycobertura pytest-html-reporter coverage
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          pip install pipenv
+          pipenv install --deploy --dev
+          pipenv install flake8 pytest pytest-cov pycobertura pytest-html-reporter coverage
+
       - name: Run unit tests
         run: |
-          coverage run --branch -m pytest tests/ --import-mode=append \
+          pipenv run coverage run --branch -m pytest tests/ --import-mode=append \
             --html-report=/reports/index.html \
             --title='IRMA UNIT TEST REPORT ${{ matrix.python-version }}'
-          coverage html -d /reports/coverage
+          pipenv run coverage html -d /reports/coverage
+
       - name: Deploy to Netlify
         uses: nwtgck/actions-netlify@v1.2
-        if: success() || failure()        # run this step even if previous step failed
+        if: success() || failure() # run this step even if previous step failed
         with:
-          publish-dir: '/reports'
+          publish-dir: "/reports"
           production-branch: master
           alias: ${{ github.head_ref }}
           github-token: ${{ secrets.GITHUB_TOKEN }}
@@ -60,6 +62,7 @@ jobs:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
         timeout-minutes: 1
+
   build-mock_mobius_docker:
     runs-on: self-hosted
     steps:
